### ISSUE TITLE
Some of code examples from README do not run successfully

### ISSUE THREAD

**Issue by melezhik** [frithnanth/Raku-Net-Whois#2]
Hi @frithnanth I am experimenting with some SparrowCI pipeline that allow me to run code example from a module readme page, and this is what I get for Raku-Net-Whois - https://ci.sparrowhub.io/report/3825 , HTH

Alexey

**Comment by frithnanth** [comment]
That's not a complete program, it's just an example. To make it work I should add a
```raku
sub MAIN(:$who, :$using)
```
But then in order to test the program your software should provide the command line parameters. That's fine if your software knows what's testing, but I don't think you want to delve into every single Raku module, learn its API, and adapt your software.

**Comment by melezhik** [comment]
is it possible then have a code example that does not use cli ?

**Comment by frithnanth** [comment]
`Net::Whois` is an interface to query the `WHOIS` protocol servers.
Usually I try to be a good network citizen and not occupy the bandwidth of other people's servers; I regret I had to query two of those servers in my test files (those under the project's `t/` directory), but I was counting on the discretion of the very few Raku users who would install my module.
So no, I won't release a code example that does not use a CLI (though there's one that does use the CLI in the project's `examples/` directory).
